### ISSUE TITLE
Divide by zero error

### ISSUE THREAD

**Issue by asalt** [Chris7/pyquant#20]
I have a divide by zero error when I run the program on a mzML file. The program seems to continue to run but the percentage remains stuck where it is.
  
  ╰─λ pyQuant --scan-file ./myfile.mzML --precursor-ppm 20 --html --out ./myfile_pyquant_test -p 6       
    --sample .05
    msparser not found, Mascot DAT files unable to be parsed 
    Loading Scans:

    Scans loaded.
    Beginning quantification.
    Processing /mnt/e/projects/pyquant-testing/myfile.mzML.

Ran fine for a while, but then:

    7.57% Completed/home/me/Virtualenvs/py35/lib/python3.5/site-packages/pyquant/worker.py:1000: 
    RuntimeWarning: divide by zero encountered in double_scalars
      coef_det = 1 - ss_res / ss_tot

Am I missing something here?

**Comment by Chris7** [comment]
Hi @asalt,

I assume you are using PyQuant v1.42 -- I am about to make a new release that addresses a lot of these issues. There is a release candidate out you may install with `pip install pyquant-ms==0.1.43rc12` -- could you repeat your analysis with that version?

If you are willing to upload your mzml files somewhere, I could also take a look at it to see if there are any issues.

**Comment by Chris7** [comment]
Closing this as I believe this is fixed in the latest release
