### ISSUE TITLE
local variable reference before assignment

### ISSUE THREAD

**Issue by emassign** [Chris7/pyquant#36]
Dear Chris7,

I am facing a problem when I try to use pyQuant.
I did one test run a long time ago, and everything worked smoothly, but now whenever I try to run the program I get this error message.
![error_capture](https://user-images.githubusercontent.com/30228942/62718412-11a35e00-ba06-11e9-8115-a390bfb1337e.PNG)

Could you please help me fix this problem?

Thank you in advance,
Enrico

**Comment by Chris7** [comment]
Can I get the command you are running this with and if possible, the files that go along wiht running it?

**Comment by Chris7** [comment]
Ah, i see the problem here, it's because you are not running with `--help`. I think some default got set somewhere that is making the command line go ahead without any parameters.

**Comment by Chris7** [comment]
Fixed in latest version
