### ISSUE TITLE
Problem with PyQuant

### ISSUE THREAD

**Issue by emassign** [Chris7/pyquant#37]
![Capture-error](https://user-images.githubusercontent.com/30228942/64408283-9fff1400-d086-11e9-8ee0-6cf1b382fda6.PNG)

Dear Chris7,
I am running pyQuant using the code:
>pyQuant --tsv evidence.txt --label-method K8R10 --maxquant --html

However I am getting the the error message that I have attached.
Could you please help me?

Thanks in advance,
Enrico

**Comment by Chris7** [comment]
How are you running pyquant (docker or a system install, and if so, what version?)?

I have a release coming up that changes a few things with how Maxquant files are being processed that may address this. But it also may be a pandas version, where the way I was indexing previously was acceptable but is now not. If possible, could I get your evidence.txt file and the results of pip freeze if you are running it on your system?

**Comment by emassign** [comment]
Dear Chris7,
I installed pyQuant in a conda environment (OS of the machine is Linux).
I am attaching the results of pip freeze: [pip_freeze.txt](https://github.com/Chris7/pyquant/files/3589154/pip_freeze.txt)

Do you also need the input files? I could not attach them because they are too big, so I put them on wetransfer. here's the link to download them: https://we.tl/t-ues5gbiFoc

Thank you,
Enrico

**Comment by Chris7** [comment]
This looks to be fixed in the current branch of pyquant. I am having some issues with the machine that builds on windows (app-veyor) so I need to get that fixed to release an official windows version.

**Comment by Chris7** [comment]
There is a windows test release, that can be installed via `pip install pyquant==0.3.0rc0`

**Comment by Chris7** [comment]
Feel free to reopen if the latest does not resolve this.
